# Movimiento con aceleración constante

$$
\definecolor{magenta}{RGB}{255,0,144}
\newcommand{\cparentesis}[1]{ {\color{magenta} #1} }
\newcommand{\iprn}{\cparentesis{(}}
\newcommand{\fprn}{\cparentesis{)}}
\newcommand{\ii}{{\rm i}}
\newcommand{\ff}{{\rm f}}
$$

$$
a_x \iprn t_\ii \fprn = a_x \iprn t_\ff \fprn = {\rm constante} \\
$$

$$
v_x\iprn t_\ff \fprn  = v_x\iprn t_\ii \fprn + a_x\iprn t_\ii \fprn \big( t_\ff - t_\ii \big) 
$$ {#eq-1d-aceleracion-constante-vel}


$$
x\iprn t_\ff \fprn  = x\iprn t_\ii \fprn + v_x\iprn t_\ii \fprn \big( t_\ff - t_\ii \big) + \frac{1}{2} a_x\iprn t_i \fprn \big( t_\ff - t_\ii \big)^2
$$ {#eq-1d-aceleracion-constante-pos}

$$
v_x^2\iprn t_\ff \fprn = v_x^2\iprn t_\ii \fprn + 2a_x \iprn t_i \fprn \big(  x\iprn t_\ff \fprn - x\iprn t_\ii \fprn \big)
$$ {#eq-1d-aceleracion-constante-vel2}

::: {.column-margin}
::: {.justify}
Teorema fundamental del cálculo. Sea la derivada de $f$ una función de variable real continua en el intervalo $[a,b]$, entonces
:::
$$
\int_a^b \bigg( \frac{d}{dt} f \bigg) dt = f(b) -f(a)
$$ 
:::

::: {.callout-note appearance="simple" icon=false collapse="true"}
## Deducción de @eq-1d-aceleracion-constante-vel
De acuerdo con el Teorema Fundamental del Cálculo tenemos que:
$$
\int_{t_\ii}^{t_\ff} a_x\iprn t \fprn \,dt =\int_{t_\ii}^{t_\ff} \bigg( \frac{d}{dt} v_x \bigg)dt  = v_x\iprn t_\ff \fprn - v_x\iprn t_\ii \fprn
$$
Realizamos la integral de la aceleración
$$
\int_{t_\ii}^{t_\ff} a_x\iprn t \fprn \,dt = a_x(t_i) \int_{t_\ii}^{t_\ff} \,dt = a_x(t_i)\big( t_f - t_i \big)
$$
Juntando ambas expresiones
$$
v_x\iprn t_\ff \fprn - v_x\iprn t_\ii \fprn = a_x(t_\ii)\big( t_\ff - t_\ii \big)
$$
Entonces,
$$
v_x\iprn t_\ff \fprn = v_x\iprn t_\ii \fprn + a_x(t_i)\big( t_\ff - t_\ii \big)\,.
$$
:::

::: {.callout-note appearance="simple" icon=false collapse="true"}
## Deducción de @eq-1d-aceleracion-constante-pos
Con el fin de determinar la posición necesitamos $v_x\iprn t \fprn$. En el caso de aceleración constante, 
$$
v_x\iprn t \fprn = v_x\iprn t_\ii \fprn + a_x(t_i)\big( t - t_\ii \big)\,.
$$
Utilizando el Teorema Fundamental del Cálculo tenemos

$$
\int_{t_\ii}^{t_\ff} v_x\iprn t \fprn \,dt =\int_{t_\ii}^{t_\ff} \bigg( \frac{d}{dt} x \bigg)dt  = x\iprn t_\ff \fprn - x\iprn t_\ii \fprn
$$

Ahora realicemos la integral con la expresión de la velocidad anterior

$$
\int_{t_\ii}^{t_\ff} v_x\iprn t \fprn \,dt = \int_{t_\ii}^{t_\ff} v_x\iprn t_\ii \fprn + a_x \iprn t_i \fprn \big( t - t_\ii \big) \,dt
$$

$$
\int_{t_\ii}^{t_\ff} v_x\iprn t \fprn \,dt = v_x\iprn t_\ii \fprn\big( t_\ff -t_\ii \big) + \frac{1}{2}a_x \iprn t_i \fprn \big( t_\ff - t_\ii \big)^2
$$

Juntando ambas expresiones,
$$
x\iprn t_\ff \fprn - x\iprn t_\ii \fprn = v_x\iprn t_\ii \fprn\big( t_\ff -t_\ii \big) + \frac{1}{2}a_x \iprn t_i \fprn \big( t_\ff - t_\ii \big)^2
$$
Por lo tanto,

$$
x\iprn t_\ff \fprn = x\iprn t_\ii \fprn + v_x\iprn t_\ii \fprn\big( t_\ff -t_\ii \big) + \frac{1}{2}a_x \iprn t_i \fprn \big( t_\ff - t_\ii \big)^2
$$
:::


::: {.callout-note appearance="simple" icon=false collapse="true"}
## Deducción de @eq-1d-aceleracion-constante-vel2

De la ecuación @eq-1d-aceleracion-constante-vel es posible despejar $(t_\ff-t_\ii)$

$$
(t_\ff-t_\ii) = \frac{v_x(t_\ff)-v_x(t_\ii)}{a_x(t_\ii)}
$$

y sustituir en la ecuación @eq-1d-aceleracion-constante-pos 
$$
x\iprn t_\ff \fprn = x\iprn t_\ii \fprn + v_x\iprn t_\ii \fprn\bigg( \frac{v_x \iprn t_\ff \fprn-v_x \iprn t_\ii \fprn}{a_x \iprn t_\ii \fprn} \bigg) + \frac{1}{2}a_x \iprn t_i \fprn \bigg( \frac{v_x \iprn t_\ff \fprn-v_x \iprn t_\ii \fprn}{a_x \iprn t_\ii \fprn} \bigg)^2
$$


$$
x\iprn t_\ff \fprn  - x\iprn t_\ii \fprn = \frac{ v_x\iprn t_\ii \fprn v_x\iprn t_\ff \fprn - v_x^2\iprn t_\ii \fprn  }{a_x \iprn t_\ii \fprn}+\frac{1}{2}\frac{ v_x^2\iprn t_\ff \fprn - 2 v_x\iprn t_\ii \fprn v_x\iprn t_\ff \fprn  + v_x^2\iprn t_\ii \fprn  }{a_x \iprn t_\ii \fprn}
$$ 

$$
2 a_x \iprn t_\ii \fprn (x\iprn t_\ff \fprn  - x\iprn t_\ii \fprn ) = 2v_x\iprn t_\ii \fprn v_x\iprn t_\ff \fprn - 2v_x^2\iprn t_\ii \fprn + v_x^2\iprn t_\ff \fprn - 2 v_x\iprn t_\ii \fprn v_x\iprn t_\ff \fprn  + v_x^2\iprn t_\ii \fprn 
$$
$$
2 a_x \iprn t_\ii \fprn (x\iprn t_\ff \fprn  - x\iprn t_\ii \fprn ) = v_x^2\iprn t_\ff \fprn - v_x^2\iprn t_\ii \fprn 
$$

Por lo tanto,
$$
v_x^2\iprn t_\ff \fprn = v_x^2\iprn t_\ii \fprn  + 2 a_x \iprn t_\ii \fprn (x\iprn t_\ff \fprn  - x\iprn t_\ii \fprn ) 
$$
:::