project:
  type: book
  output-dir: docs
  render:
    - "*.qmd"

book:
  title: "FI"
  author: "JEBV"
  date: "8/21/2023"
  chapters:
    - index.qmd
    - part: "U1. Elementos básicos"
      chapters:
        - 1_1_magnitudesfisicas.qmd
        - 1_2_conversionunidades.qmd
        - 1_3_dimensiones.qmd
        - 1_4_ejerciciosdimensiones.qmd
        - 1_5_teoremaPI.qmd
        - 1_6_graficasdefunciones.qmd
    - part: "U2. Movimiento en una dimensión"
      chapters: 
        - 2_1_intromovimiento.qmd
        - 2_2_movimiento1D.qmd
        - 2_2_1_movimientoacero.qmd
        - 2_2_2_movimientoacte.qmd
        - 2_2_3_movimientoavar.qmd
        - 2_3_ejercicios1D.qmd
    - part: "U3. Vectores y movimiento en más de una dimensión"
      chapters:
        - 3_1_vectores.qmd
    - part: "U4. Las leyes de movimiento"
    - part: "U5. Energía"
    - part: "U6. Cantidad de movimiento y choques"
    - part: "U7. Movimiento rotacional"
    - part: "U8. Equilibrio rotacional y dinámica rotacional"
    - part: "Apéndice. Mathematica by Wolfram."
      chapters:
        - A_math_derivadasintegrales.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: united
      dark: slate
    css: style.css
    toc: true
    toc-title: Contenido
  pdf:
    documentclass: scrreprt



